accounts/urls.py
# In a new app, you must make a urls.py file and then import these two

from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup_view, name="signup"), 
  path('login/', views.login_view, name="login"),
  path('logout/', views.logout_view, name="logout")
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles' # this is to prevent confusion for the name="list". if you have another app that uses name="list" then this will help differentiate

urlpatterns = [
    path('', views.article_list, name="list"), # the name urls seem liek a variable that helps to simplify calling the root in another function
    path('create/', views.article_create, name="create"), # always have custom URLs BEFORE the slug so that django wont think this url is part of the SLUG
    path('<slug:slug>/', views.article_detail, name="detail") # similar to params in node express
]



# SLUGS IN MODERN DJANGO a.k.a. similar to params in Node.js !!

# This has been significantly changed in Django 3, this could be done like this:
# path('<slug:slug>/', views.article_detail), YOU MUST ADD the forward slash
# where the first slug "<slug" is the type of the passed parameter which is a slug in our case, 
# and the second slug ":slug>" is the name of the parameter which could be any name; "abc", "the_slug", etc.

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views # we make views as articles_views so django wont get confused with the other views of the root folder

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), # new apps need to be registered in the main app
    path('articles/', include('articles.urls')),
    path('about/', views.about),
    path('', article_views.article_list, name="home")
]

# Below is telling Django how we serve up the static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #static files that have been uploaded to django

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.urls.converters import SlugConverter
from django.contrib.auth.models import User # import user model as a foreign key in Articles model

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True) # automatically add the date of NOW
    thumb = models.ImageField(default='default.png', blank=True) # data field for image / default image if no image / blank =True - it can be a blank field and not requried
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None) # a function for SQL where when this foreign key is deleted it will cascade down to the related table and end up deleting the corresponding keys

    # the function below makes the title of each instance of the article visible in the Query Article.objects.all()
    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[:50] + '...'

# The Command Lines for Migrations - Whenever you make changes (add or remove) you always make migrations to the database
  # python manage.py makemigrations    <---- make a migration file
  # python manage.py migrate   <--- migrate the changes to the database

articles/forms.py
from django import forms
from . import models # we need access to model 

# making a custom form
class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.

# making the account
def signup_view(request):
    if request.method == 'POST':
      form = UserCreationForm(request.POST)
      if form.is_valid():
        user = form.save() # returns a user info
        login(request, user)
        return redirect('articles:list')
    else:
      form = UserCreationForm() # this is an instance of the form which below we will send down to the template
    return render(request, 'accounts/signup.html', {'form':form})

# logging the user in
def login_view(request): # name ur login  views with login_views
    if request.method == 'POST':
      form = AuthenticationForm(data=request.POST) # we name data = request.POST because it is not he first instance of the data??
      if form.is_valid():
        user = form.get_user() # retrieve user informatio when its trying to login
        login(request, user) # logins the user
        if 'next' in request.POST:
            return redirect(request.POST.get('next')) # gets the next query in the url
        else:
            return redirect('articles:list')
    else: 
      form = AuthenticationForm() # django-made login form
    return render(request, 'accounts/login.html', {'form': form}) # inject the form into the front end

#logout users
def logout_view(request):
    # always make a POST request to logout and NOT a GET request
    if request.method == 'POST':
       logout(request)
       return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms # import forms
# In order to inject the article model data into the HTML we need to import the article models
# and then render it into the function below

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug) # goes to the models of the database to find the article with the corresponding slug
    return render(request, 'articles/article_detail.html', {'article': article}) # the article with 'quotations' is like a variable, you can call it whatever u want. With that variable we are sending in the article data

# use python django decorators to protect this view. First import from django.contrib. This redirects to the login page
# this decorator indicates that article_create is a protected URl
@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES) # files are separate 
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False) # commit=False means before saving, we're going process the instance 
            instance.author = request.user # associate the author with the user logged in 
            instance.save()
            return redirect('articles:list')
    else: # if request is a GET request
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

## never fucking remove the git remove function 
# First we make a variable equal to the Model class and grab the data by .objects.all() method. This will return a list (array)
# then we can add another method to sort the list in an order we want .order_by() anything define 
# the render method takes in a third argument which accepts a dictionary (object) and tells which data to render. In this case the articles variable 

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Login</h1>
<form action="{% url 'accounts:login' %}" class="site-form" method="post">
  {% csrf_token %}
  <!-- We need csrf token for security reasons like JSON web token wihout it we cannot log in -->
  {{ form }}
  <!-- if user is logging in other than the articles list page -->
  {% if request.GET.next %}
  <input type="hidden" name="next" value="{{ request.GET.next}}" />
  {% endif %}
  <input type="submit" value="Login" />
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Sign up!</h1>
<form action="/accounts/signup/" class="site-form" method="post">
  {% csrf_token %}
  <!-- We need csrf token for security reasons like JSON web token wihout it we cannot log in -->
  {{ form }}
  <input type="submit" value="Sign up!" />
</form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %} {% block content %}
<div class="create-article">
  <h2>Create an Awesome New Article</h2>
  <form
    action="{% url 'articles:create' %}"
    method="post"
    class="site-form"
    enctype="multipart/form-data"
  >
    {% csrf_token %} {{ form }}
    <input type="submit" value="Create" />
  </form>
</div>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

<!--  Block content -->
{% block content %}
<div class="article-detail">
  <div class="article">
    <img src="{{ article.thumb.url}}" />
    <h2>{{ article.title }}</h2>
    <p>{{ article.body }}</p>
    <p>{{ article.date }}</p>
  </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
<!-- This is letting Django know that we need to extend the base_layout here -->

<!-- Block content and endblock template tags is letting know Django this is the thing that needs to inject into base layout -->
{% block content %}
<h1>Article List</h1>
<div class="articles">
  {% for article in articles %}
  <div class="article">
    <h2>
      <a href="{% url 'articles:detail' article.slug %}">{{ article.title }}</a>
    </h2>
    <!-- Below the article.snippet is called to shorten the body. It is processed already in the models sections -->
    <p>{{ article.snippet }}</p>
    <p>{{ article.date }}</p>
    <p class="author">added by {{ article.author.username }}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}

<!-- In Django 3:
{% url 'detail' article.slug %}
No need for "slug=" -->

templates/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>About</title>
  </head>
  <body>
    <h2>This is the about page</h2>
  </body>
</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css'%}" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;1,400&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="wrapper">
      <a href="{% url 'home' %}"><img src="{% static 'logo.png'%}" /></a>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <form
              class="logout-link"
              action="{% url 'accounts:logout' %}"
              method="post"
            >
              {% csrf_token %}
              <!-- Every post request you must include the csrf token for security resons -->
              <button type="submit">Logout</button>
            </form>
          </li>
          <li>
            <a href="{% url 'articles:create' %}" class="highlight"
              >New Article</a
            >
          </li>
          {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Homepage</title>
  </head>
  <body>
    <h2>Hello This is the homepage</h2>
  </body>
</html>